Module3 task1
htmlacademy-ecmascript/679669-big-trip-13 pull request #5
Opened 2020-12-23 12:47 UTC by squaredbusinessman

каша в голове и каша в коде, не пойму за что хвататься(

2020-12-24 07:20 UTC, Dima-Dim requested changes
Подкорректировать нейминг, что бы экспортируемый класс совпадал с названием файла.
Сделать классы там где их ещё нет.
https://htmlacademy-ecmascript.github.io/679669-big-trip-13/5/ - должно собираться и работать, как и локально.
Локально в блок с классом trip-info__cost-value должна попадать разметка, а не JS код.

2020-12-24 07:20 UTC, Dima-Dim commented on src/utils.js
> +  }
Хорошо бы иметь default.

2020-12-24 07:20 UTC, Dima-Dim commented on src/view/trip-event.js
> +export default class TripWaypoint {
Если файл называется trip-event.js, то из него мы экспортируем TripEvent.js
И наоборот, если мы хотим экспортировать TripWaypoint то файл нужно назвать trip-waypoint.js

2020-12-24 07:20 UTC, Dima-Dim commented on src/view/trip-event-offers.js
> +export const renderOffers = (offers) => {
Почему не класс?

2021-01-21 17:15 UTC, Dima-Dim requested changes
Хорошо бы решить проблему с путями для стилей и бандла, чтобы сборка https://htmlacademy-ecmascript.github.io/679669-big-trip-13/5/ работала нормально.

2021-01-21 17:15 UTC, Dima-Dim commented on src/mock/generate-dates.js
> +    const minMinuteDifference = 15;
https://up.htmlacademy.ru/ecmascript/13/criteries#b5

2021-01-21 17:15 UTC, Dima-Dim commented on src/mock/generate-trip-events.js
> +    counter: incCounter(),
Если это вместо ID, то лучше явно указать что это id и для его генерации использовать nanoid, в лекциях о нём говориться.

2021-01-22 10:29 UTC, squaredbusinessman commented
> Хорошо бы решить проблему с путями для стилей и бандла, чтобы сборка https://htmlacademy-ecmascript.github.io/679669-big-trip-13/5/ работала нормально.

Сделал

2021-01-22 10:29 UTC, closed without merging